name: MooDialog
author: astolwijk
current: 0.8
category: Interface
tags: [Dialog, Modal, Box, Alert, Confirm, Ajax, IFrame]
demo: http://www.aryweb.nl/projects/MooDialog/
docs: http://github.com/arian/MooDialog/blob/master/README.md

copyright: "Arian Stolwijk"
license: MIT
web: "[aryweb.nl/projects/MooDialog](http://www.aryweb.nl/projects/MooDialog/)"
description: MooTools Dialog/Modal Classes

sources:
  - "Source/MooDialog.js"
  - "Source/MooDialog.Fx.js"
  - "Source/MooDialog.Alert.js"
  - "Source/MooDialog.Confirm.js"
  - "Source/MooDialog.Error.js"
  - "Source/MooDialog.IFrame.js"
  - "Source/MooDialog.Prompt.js"
  - "Source/MooDialog.Request.js"
  - "Source/Overlay.js"
